# Generated by Django 5.0 on 2023-12-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_student_teacher_alter_school_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.CharField(default=788904, max_length=8),
        ),
    ]
