# Generated by Django 5.0 on 2023-12-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Username',
            field=models.CharField(default=865, max_length=12),
        ),
    ]
