# Generated by Django 5.0 on 2023-12-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_student_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Password',
            field=models.CharField(default=786, max_length=8),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Username',
            field=models.CharField(default=879, max_length=12),
        ),
    ]
