# Generated by Django 5.0 on 2023-12-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_teacher_password_teacher_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cls',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Subject',
            field=models.CharField(default='maths', max_length=21),
        ),
    ]
