# Generated by Django 5.0 on 2023-12-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_student_cls_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Username',
            field=models.CharField(default='student', max_length=12),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Username',
            field=models.CharField(default='Teacher', max_length=12),
        ),
    ]
